### ISSUE TITLE
Compatibility Issue with new version of TAXII, STIX, Cybox

### ISSUE THREAD

**Issue by angreebunny** [AlienVault-Labs/OTX-Apps-TAXII#4]
i first saw this issue in forums post https://forums.soltra.com/index.php?/topic/681-alient-vault-otx/ posted and was able to replicate the error. I have resolved it, and will submit a pull request against this issue

submitted by qianru.c (18 September 2016 - 02:16 AM)
> C:\Users\W\OTX-Apps-TAXII-master>python otx-taxii.py check_new
> Traceback (most recent call last):
>   File "otx-taxii.py", line 2, in <module>
>     from StixExport import StixExport
>   File "C:\Users\W\OTX-Apps-TAXII-master\StixExport.py", line 16, in <module>
>     from stix.utils import set_id_namespace
> ImportError: cannot import name set_id_namespace

submitted by mdargie (11 January 2017 - 08:25 PM)
```[root@localhost OTX-Apps-TAXII]# python otx-taxii.py first_run
Traceback (most recent call last):
  File "otx-taxii.py", line 1, in <module>
    from StixExport import StixExport
  File "/home/OTX/OTX-Apps-TAXII/StixExport.py", line 1, in <module>
    from stix.core import STIXPackage, STIXHeader
  File "/usr/lib/python2.6/site-packages/stix/__init__.py", line 5, in <module>
    from .base import Entity, EntityList, TypedList, BaseCoreComponent  # noqa
  File "/usr/lib/python2.6/site-packages/stix/base.py", line 11, in <module>
    from . import bindings, utils
  File "/usr/lib/python2.6/site-packages/stix/utils/__init__.py", line 338, in <module>
    from .nsparser import *  # noqa
  File "/usr/lib/python2.6/site-packages/stix/utils/nsparser.py", line 433, in <module>
    (ns, loc) for ns, _, loc in cybox.utils.nsparser.NS_LIST if loc
AttributeError: 'module' object has no attribute 'NS_LIST'```

**Comment by chrisdoman** [comment]
Thanks appreciate the update! Merged.

I've tested it and fixed one other issue I was having locally with a library.

Let us know if this doesn't work or anything else is broken

**Comment by angreebunny** [comment]
tested: no issues
